spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect
      format-sql: true  
  datasource:
    url: jdbc:mariadb://localhost:3306/mudidb
    username: root
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver  