spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect
      hibernate:
        '[format_sql]': true 
  datasource:
    url: jdbc:mariadb://localhost:3306/mudidb
    username: root
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver  
    
  flyway:
    enabled: true